//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetallePlato
    {
        public int idPlato { get; set; }
        public int idCliente { get; set; }
        public int idMesa { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblMesa tblMesa { get; set; }
        public virtual tblPlato tblPlato { get; set; }
    }
}
